In [2]:
# Import all libraries which is related to your output
import pandas as pd # pandas we use for read the output
from sklearn.tree import DecisionTreeClassifier # scrikit-learn library used in machine learning
# and it draw decision tree and how to tree make decison as per your output

In [3]:

# Create own dataset and variable name = data
data = {
    "Weather": ["Sunny", "Cloudy", "Sunny", "Cloudy", "Rainy", "Rainy", "Rainy", "Sunny", "Cloudy", "Rainy"],
    "Temperature": ["Hot", "Hot", "Mild", "Mild", "Mild", "Cool", "Mild", "Hot", "Hot", "Mild"],
    "Humidity": ["High", "High", "Normal", "High", "High", "Normal", "High", "High", "Normal", "High"],
    "Wind": ["Weak", "Weak", "Strong", "Strong", "Strong", "Strong", "Weak", "Strong", "Weak", "Strong"],
    "Play": ["No", "Yes", "Yes", "Yes", "No", "No", "Yes", "No", "Yes", "No"]
}

In [4]:
# here df means dataframe to represent ur data in form of row and columns
df = pd.DataFrame(data)
df

  Weather Temperature Humidity    Wind Play
0   Sunny         Hot     High    Weak   No
1  Cloudy         Hot     High    Weak  Yes
2   Sunny        Mild   Normal  Strong  Yes
3  Cloudy        Mild     High  Strong  Yes
4   Rainy        Mild     High  Strong   No
5   Rainy        Cool   Normal  Strong   No
6   Rainy        Mild     High    Weak  Yes
7   Sunny         Hot     High  Strong   No
8  Cloudy         Hot   Normal    Weak  Yes
9   Rainy        Mild     High  Strong   No

In [5]:

# Convert text data to Numeric data beacuse machine can't understand ur text data
# this all process name is Label Encoding
# repalce means text to numeric
df_encoded = df.replace({"Sunny":0, "Cloudy":1, "Rainy":2,
                        "Hot":0, "Mild":1, "Cool":2,
                        "High":0, "Normal":1,
                        "Weak":0, "Strong":1,
                        "No":0, "Yes":1})

/tmp/ipykernel_677/3013710192.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_encoded = df.replace({"Sunny":0, "Cloudy":1, "Rainy":2,

In [6]:
df_encoded # for print your data

   Weather  Temperature  Humidity  Wind  Play
0        0            0         0     0     0
1        1            0         0     0     1
2        0            1         1     1     1
3        1            1         0     1     1
4        2            1         0     1     0
5        2            2         1     1     0
6        2            1         0     0     1
7        0            0         0     1     0
8        1            0         1     0     1
9        2            1         0     1     0

In [7]:
# Separate input and output
X = df_encoded.drop("Play", axis=1) # here u can drop play attribute and axis = 1 means remove column (not rrow)
y = df_encoded["Play"] # here u can use play aattribute as a y

In [8]:
X

   Weather  Temperature  Humidity  Wind
0        0            0         0     0
1        1            0         0     0
2        0            1         1     1
3        1            1         0     1
4        2            1         0     1
5        2            2         1     1
6        2            1         0     0
7        0            0         0     1
8        1            0         1     0
9        2            1         0     1

In [9]:
y

0    0
1    1
2    1
3    1
4    0
5    0
6    1
7    0
8    1
9    0
Name: Play, dtype: int64

In [12]:
# Train Decicion Tree model
model = DecisionTreeClassifier() # here u can fir model , desicion tree model is totally blank
model.fit(X,y) # here u can fir your data in the form of x and y
# x = Weather, Temperature, Humidity, Wind
#y = output labels

DecisionTreeClassifier()

In [13]:
print("\n Model Trained") # it's shows your model is trained for prediction
# because u fit here in the basis of x and y

 Model Trained

In [14]:
# Make a sample prediction
sample = [[1,1,0,0]] # here u can create ur own sample data for predicition
prediction = model.predict(sample)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [15]:
if prediction[0] == 1:
  result = "play"
else:
  result = "Don't Play"

print(result)

play